### ISSUE TITLE
Authentication works but stuck on spinning loop

### ISSUE THREAD

**Issue by gabedeko** [kmaida/auth0-ionic3-samples#1]
Similar to the issue I had with the current Ionic 2+ sample [here](https://auth0.com/docs/quickstart/native/ionic2), after authenticating(which is successful) nothing happens and the spinner goes into an infinite loop. Is there a way to redirect the user back to the homepage of the app after authentication is successful?

**Comment by ankit-ilogix** [comment]
@kmaida I am facing same issue of spinning loop on ios devices and getting below error.
On android device browser window is close after authentication but below error is also comming.

**Note: Below error is only getting first time Authentication.**  

"Uncaught Error: Response state does not match expected state
    at Function.<anonymous> (vendor.js:83515)
    at Function.Session.onRedirectUri (vendor.js:155066)
    at vendor.js:83559
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at e.invokeTask (polyfills.js:3)
    at i.isUsingGlobalCallback.invoke (polyfills.js:3)
    at n (polyfills.js:3)"

Please give your help/suggestion for the same.

**Comment by kmaida** [comment]
@gabedeko @ankit-ilogix Did you follow all instructions in the repo README regarding configuring redirection with `cordova-plugin-customurlscheme`? https://github.com/kmaida/auth0-ionic3-samples/tree/master/01-Login

The repo contains this plugin to start with right now (it will be removed before the Quick Start is published), so you will need to remove it and re-install it with your own appropriate settings in order to get a clean configuration state. 

```
ionic cordova plugin remove cordova-plugin-customurlscheme
ionic cordova plugin add cordova-plugin-customurlscheme --variable URL_SCHEME=com.auth0.ionic --variable ANDROID_SCHEME=com.auth0.ionic --variable ANDROID_HOST={your_Auth0_domain} --variable ANDROID_PATHPREFIX=/cordova/com.auth0.ionic/callback
```

**Comment by ankit-ilogix** [comment]
@kmaida @gabedeko  Your suggestion was I tried but same issue I am facing with it. 

After that I found issue in hosted page when I am create account before some days that time in password less default hosted page using "lock-passwordless-2.2.min.js" today I create new account in Auth0.  In new account's passwordless default hosted page containing   "js/lock/11.2/lock.min.js".

Now thats working fine with me thanks.

**Comment by kmaida** [comment]
Hi @ankit-ilogix,

You should not need to create a new account. You can change the hosted login page type (from Passwordless to Lock) in the dropdown in its settings, like so:

<img width="344" alt="screen shot 2018-02-08 at 8 50 58 am" src="https://user-images.githubusercontent.com/1884525/35976196-5a389174-0cad-11e8-85dc-d240680e6d93.png">

In any case, glad this was resolved for you!

**Comment by ankit-ilogix** [comment]
for now the response state issue is resolved but I am facinng new below issue.
1. For android after first time successfully login if I click on logout (window.localStorage.removeItem('profile');
    window.localStorage.removeItem('access_token');
    window.localStorage.removeItem('id_token');
    window.localStorage.removeItem('expires_at');)  after that I click on login that time also logged in. It means logout not working for me only on android.

2 For IOS I am facing CORS issue . I have added also url on client settings but I dont know why that not working. First time browser is close and is redirect to login page when I click on further login page than it will open safari page with title "window" . after If I clear browser cooker than working fine. 

@kmaida  Please give your help/ suggestion for the same thanks.

**Comment by kmaida** [comment]
@ankit-ilogix @gabedeko Please hold off on this implementation. While this repo does and should work without any issues currently, we are in the process of rewriting the auth0-cordova library, which is the primary dependency for this quick start. We should have that completed by this weekend and then will have the fully re-written Ionic example and quick start written in the weeks following, either late February or early March. Thanks for your patience while we make these improvements!

**Comment by ankit-ilogix** [comment]
@kmaida  Please alert me when Auth0 complete process of rewriting the auth0-cordova library. 
thanks.

**Comment by gabedeko** [comment]
@kmaida On my end it's fairly urgent that I'm able to use the login system without issue but I am still experiencing the infinite loop but I'm pretty sure I've followed the steps accurately.

**Comment by darkyen** [comment]
@ankit-ilogix CORS issue is currently thrown because of WKWebView in Ionic which is a browser context running at http://localhost:8080. Using `POST /oauth/token` is not allowed from browser context and therefore does not respond with CORS. I am currently working on updating the underlying plugin to use `native` http layer which bypasses this and will update it upstream. For now the best way to handle this is to use UIWebView until I fix the issue.

**Comment by darkyen** [comment]
@gabedeko if you are using WKWebView  you'll run into the same.

**Comment by gauravatinsightmethods** [comment]
@kmaida Are Auth0 complete rewriting the auth0-cordova library OR not?

**Comment by gabedeko** [comment]
@ankit-ilogix I am not running the app from a desktop browser. I'm only running it from a mobile device.

@kmaida I'd also like to know when the rewrite will be complete.

**Comment by kmaida** [comment]
@gauravatinsightmethods @gabedeko @ankit-ilogix The Ionic 3 Quick Start is now live: https://auth0.com/docs/quickstart/native/ionic3

This repo will now be archived. Please refer to the Quick Start for the new repo.
